# -*- encoding: utf-8 -*-
#
# OpenERP Rent - A rent module for OpenERP 6
# Copyright (C) 2010-Today Thibaut DIRLIK <thibaut.dirlik@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import datetime

from osv import osv, fields

class Rent(osv.osv):

    """
    Represents the leasing of a product, which is defined by :
     - A begin and an end date.
     - The products which are rented.
     - The partner (client) they are rented to.
     - The invoice generated by this rent.

    Only products that are marked as 'rentable' can be rented. See the rent_product.py
    file to see what changed in the product model.
    """

    _name = 'rent.rent'

    _columns = {
        'begin_date' : fields.datetime('Rent start', required=True),
        'end_date' : fields.datetime('End of rental', required=True),
        'product_ids' : fields.many2many('product.product', 'rent_products_relation', 'rent_id', 'product_id',
                                         'Products', domain=[('rental', '=', 'True')], required=True),
        'partner_id' : fields.many2one('res.partner', 'Client', ondelete='restrict', required=True,
                                       domain=[('customer', '=', True)])
    }

Rent()
